pipeline{
    agent {
        label "Agent-1"
    }
    options{
        timeout(time: 20, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters{
        choice(name: 'Action', choices: ['apply', 'destroy'], description: 'Select the action to perform')
    }
    stages{
        stage('Terraform Init'){
            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'terraform-aws-credentials'){
                        sh """
                        cd 10-vpc
                        terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('Terraform Plan'){
            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'terraform-aws-credentials'){
                        sh """
                        cd 10-vpc
                        terraform plan -out=tfplan
                        """
                    }
                }
            }
        }
        stage('Terraform Apply'){
            steps{
                script{
                    if(params.Action == 'apply'){
                        withAWS(region: 'us-east-1', credentials: 'terraform-aws-credentials'){
                            sh 'terraform apply -auto-approve -out=tfplan'
                        }
                    elif(params.Action == 'destroy'){
                        withAWS(region: 'us-east-1', credentials: 'terraform-aws-credentials'){
                            sh 'terraform destroy -auto-approve'
                        }
                    }
                    }
                }
            }
        }
    }
    post{
        always {
            echo "This is post section, it will runs everytime of pipeline triggered"
            deleteDir()  // this will cleans the directory once the pipeline is completed.
        }
        success{
            echo "This is success section, it will runs when pipeline is success"
        }
        failure{
            echo "This is failure section, it will runs when pipeline is failed"
        }
    }
}