pipeline {
    agent {
        label "Agent-1"
    }
    options {
        timeout(time: 20, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'Action', choices: ['apply', 'destroy'], description: 'Select the action to perform')
    }
    stages {
        stage('Terraform Init') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'terraform-aws-credentials') {
                        sh """
                        cd 20-sg
                        terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'terraform-aws-credentials') {
                        sh """
                        cd 20-sg
                        terraform plan -out=tfplan
                        """
                    }
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                script {
                    if (params.Action == 'apply') {
                        withAWS(region: 'us-east-1', credentials: 'terraform-aws-credentials') {
                            sh """
                            cd 20-sg
                            terraform apply "tfplan"
                            """
                        }
                    } else if (params.Action == 'destroy') {
                        withAWS(region: 'us-east-1', credentials: 'terraform-aws-credentials') {
                            sh """
                            cd 20-sg
                            terraform destroy -auto-approve
                            """
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            echo "This is post section, it will run every time the pipeline is triggered"
            deleteDir()  // this will clean the directory once the pipeline is completed.
        }
        success {
            echo "This is the success section, it will run when the pipeline is successful"
        }
        failure {
            echo "This is the failure section, it will run when the pipeline fails"
        }
    }
}
